sudo: required
dist: xenial
language: go
go:
    - 1.x
    - master
matrix:
    allow_failures:
        - go: master
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-lxc/lxc-git-master
    - sudo add-apt-repository -y ppa:projectatomic/ppa
    - sudo apt-get update
    - sudo apt-get install -yy skopeo
    - go get github.com/openSUSE/umoci/cmd/umoci
    - curl https://glide.sh/get | sh
    - sudo cp $GOPATH/bin/umoci /usr/bin
install: make
script:
    - make check
